image:
  registry:
  repository: payment
  tag: latest  # will be replaced
  pullPolicy: Always

namespace: qtapp

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi
env:
  GIN_MODE: debug
  GIN_ACCESS_LOG: true

service:
  name: payment
  serviceType: ClusterIP
  internalPort: 8080
  externalPort: 8080