version: "2.4"
services:
  mysql:
    image: mysql:8.0
    restart: always
    tty: true
    cap_add:
      - SYS_NICE
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
       - '3306:3306'
#  frontend:
#    image: signoz/golang-distributed-tracing:frontend
#    restart: unless-stopped
#    ports:
#      - "8080:80"
#    volumes:
#      - ./nginx.conf:/etc/nginx/conf.d/default.conf
#      - ./config.js:/usr/share/nginx/html/static/config.js
#    depends_on:
#      - backend
#      - mysql
#  backend:
#    image: signoz/golang-distributed-tracing:backend
#    restart: unless-stopped
#    # ports:
#    #   - "8080:8080"
#    #   - "8081:8081"
#    #   - "8082:8082"
#    extra_hosts:
#      - signoz:host-gateway
#    environment:
#      # service config
#      - USER_URL=0.0.0.0:8080
#      - PAYMENT_URL=0.0.0.0:8081
#      - ORDER_URL=0.0.0.0:8082
#      # database config
#      - SQL_USER=root
#      # - SQL_PASSWORD=password
#      - SQL_HOST=mysql:3306
#      - SQL_DB=signoz
#      # telemetry config
#      - OTEL_EXPORTER_OTLP_ENDPOINT=signoz:4317  # Replace with SigNoz OTLP endpoint, if SigNoz not running on host machine
#      - INSECURE_MODE=true
#    depends_on:
#      - mysql
