apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.service.name }}
  labels:
    name: {{ template "name" . }}
    app: {{ template "name" . }}
    app.kubernetes.io/name: {{ template "name" . }}
    app.kubernetes.io/instance: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.serviceType }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
  selector:
    name: {{ template "name" . }}
    app: {{ template "name" . }}
    app.kubernetes.io/name: {{ template "name" . }}
    app.kubernetes.io/instance: {{ template "name" . }}
