# (C) Copyright 2019-2023 Hewlett Packard Enterprise Development LP
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "name" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "name" . }}
    release: {{ .Release.Name }}
data:
  PORT: {{ .Values.service.internalPort | default "8080" | quote }}